import type { SellerQuestion } from '../types/report'
import SeverityChip from './SeverityChip'
import { SEVERITY_ORDER } from '../lib/severity'

export default function SellerQuestionPack({ questions }: { questions: SellerQuestion[] }) {
  const grouped = SEVERITY_ORDER.map((sev) => ({
    sev,
    items: questions.filter((q) => q.severity === sev),
  })).filter((g) => g.items.length > 0)

  return (
    <div className="rounded border border-slate-800 bg-slate-900/40 p-6">
      <div className="mb-1 flex items-center justify-between">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-300">
          Seller question pack
        </h2>
        <button
          onClick={() => window.print()}
          className="no-print rounded border border-slate-700 px-3 py-1.5 text-xs text-slate-300 transition hover:border-slate-500 hover:text-slate-100"
        >
          Export
        </button>
      </div>
      <p className="mb-5 text-xs text-slate-500">
        Every question generated by a red flag, grouped by severity, ready to send.
      </p>

      <div className="space-y-6">
        {grouped.map((group) => (
          <div key={group.sev}>
            <div className="mb-2">
              <SeverityChip severity={group.sev} />
            </div>
            <ol className="space-y-2">
              {group.items.map((q, i) => (
                <li key={i} className="flex gap-3 text-sm text-slate-300">
                  <span className="font-mono-num text-xs text-slate-600">{q.rule_id}</span>
                  <span>{q.question}</span>
                </li>
              ))}
            </ol>
          </div>
        ))}
      </div>
    </div>
  )
}
